[package]
name = "lock20"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_18"] }
gtk4-session-lock = "0.1"
nix = { version = "0.30", features = ["signal"] }
